{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2020-14343",
  "PublicDate": "2020-07-28T00:00:00Z",
  "References": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14343",
    "https://github.com/yaml/pyyaml/issues/420"
  ],
  "Description": "[.load() and FullLoader still vulnerable to fairly trivial RCE]",
  "UbuntuDescription": "",
  "Notes": [
    "sbeattie\u003e incomplete fix of CVE-2020-1747",
    "leosilva\u003e no fix as of 2020-08-03"
  ],
  "Bugs": [
    "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966233"
  ],
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "",
  "Patches": {
    "pyyaml": {
      "bionic": {
        "Status": "deferred",
        "Note": "2020-08-03"
      },
      "devel": {
        "Status": "deferred",
        "Note": "2020-08-03"
      },
      "focal": {
        "Status": "deferred",
        "Note": "2020-08-03"
      },
      "precise/esm": {
        "Status": "needs-triage",
        "Note": ""
      },
      "trusty": {
        "Status": "ignored",
        "Note": "out of standard support"
      },
      "trusty/esm": {
        "Status": "deferred",
        "Note": "2020-08-03"
      },
      "upstream": {
        "Status": "needs-triage",
        "Note": ""
      },
      "xenial": {
        "Status": "deferred",
        "Note": "2020-08-03"
      }
    }
  },
  "UpstreamLinks": {}
}