{
  "description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.",
  "releases": {
    "bullseye": {
      "fixed_version": "0.5.2-1",
      "repositories": {
        "bullseye": "1.5.4-2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "0.5.2-1",
      "repositories": {
        "buster": "1.5.4-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "0.5.2-1",
      "repositories": {
        "sid": "1.5.4-2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "0.5.2-1",
      "repositories": {
        "stretch": "1.5.1-4"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}