{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-13281"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "For GitLab before 13.0.12, 13.1.6, 13.2.3 a denial of service exists in the project import feature"
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13281.json",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13281.json"
        },
        {
          "name": "https://gitlab.com/gitlab-org/gitlab/-/issues/31564",
          "refsource": "MISC",
          "tags": [],
          "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/31564"
        },
        {
          "name": "https://hackerone.com/reports/687730",
          "refsource": "MISC",
          "tags": [],
          "url": "https://hackerone.com/reports/687730"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-08-13T14:16Z",
  "publishedDate": "2020-08-13T14:15Z"
}