{
  "debianbug": 854442,
  "description": "Openpyxl 2.4.1 resolves external entities by default, which allows remote attackers to conduct XXE attacks via a crafted .xlsx document.",
  "releases": {
    "bullseye": {
      "fixed_version": "2.3.0-3",
      "repositories": {
        "bullseye": "3.0.3-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "2.3.0-3",
      "repositories": {
        "buster": "2.4.9-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "2.3.0-3",
      "repositories": {
        "sid": "3.0.3-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "2.3.0-3",
      "repositories": {
        "stretch": "2.3.0-3"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}