{
  "debianbug": 875960,
  "description": "libarchive 3.3.2 suffers from an out-of-bounds read within lha_read_data_none() in archive_read_support_format_lha.c when extracting a specially crafted lha archive, related to lha_crc16.",
  "releases": {
    "bullseye": {
      "fixed_version": "3.2.2-4.1",
      "repositories": {
        "bullseye": "3.4.3-2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "3.2.2-4.1",
      "repositories": {
        "buster": "3.3.3-4+deb10u1",
        "buster-security": "3.3.3-4+deb10u1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "3.2.2-4.1",
      "repositories": {
        "sid": "3.4.3-2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "3.2.2-2+deb9u1",
      "repositories": {
        "stretch": "3.2.2-2+deb9u2",
        "stretch-security": "3.2.2-2+deb9u2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}